query ($slug: String!) {
  projects(where: {
    slug: $slug
  }) {
    title
    type
    github
    url
    appStore,
    playStore,
    description
    tags {
      title
      slug
    }
    screenshots {
      name
      url
    }
  }
}
